# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200422_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 4, 22, 20, 38, 38, 497772), verbose_name='Опубликована'),
        ),
    ]
