# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200422_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 4, 22, 22, 16, 1, 191961), verbose_name='Опубликована'),
        ),
    ]
